# Import

In [1]:
import pandas as pd

# Dataframe

In [2]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=["A", "B", "C"])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

### Size

Number of elements in this object.

In [3]:
df.size

9

### Shape

Tuple representing the dimensionality of the DataFrame.

In [4]:
df.shape

(3, 3)

### Describe

Generate descriptive statistics.

Descriptive statistics include those that summarize the central tendency, dispersion and shape of a dataset’s distribution, excluding `NaN` values.

In [5]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

## Loading in Dataframe from file.

In [6]:
from pathlib import Path

warm_up_csv_file = Path("./warm-up/coffee.csv")
warm_up_feather_file = Path("./warm-up/coffee.feather")
warm_up_parquet_file = Path("./warm-up/coffee.parquet")
bios_file = Path("./data/bios.csv")
noc_file = Path("./data/noc_regions.csv")
results_file = Path("./data/results.parquet")

In [7]:
print("Power of parquet comes with file size.")

print(f"File {warm_up_csv_file.name} size: {warm_up_csv_file.stat().st_size / 1024} KB")
print(
    f"File {warm_up_feather_file.name} size: {warm_up_feather_file.stat().st_size / 1024} KB"
)
print(
    f"File {warm_up_parquet_file.name} size: {warm_up_parquet_file.stat().st_size / 1024} KB"
)

Power of parquet comes with file size.
File coffee.csv size: 0.28125 KB
File coffee.feather size: 2.572265625 KB
File coffee.parquet size: 2.67578125 KB

### CSV

In [8]:
df = pd.read_csv(warm_up_csv_file)
df.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

### Feather

Feather is a portable file format for storing Arrow tables or data frames

In [9]:
df = pd.read_feather(warm_up_feather_file)
df.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

### Parquet

Apache Parquet is an open source, column-oriented data file format designed for efficient data storage and retrieval.

In [10]:
df = pd.read_parquet(warm_up_parquet_file)
df.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

## Functions

### Sampling

In [11]:
df.sample(3)

        Day Coffee Type  Units Sold
6  Thursday    Espresso          40
3   Tuesday       Latte          20
2   Tuesday    Espresso          30

In [12]:
df.sample(3, random_state=1)  # Always stays the same.

        Day Coffee Type  Units Sold
3   Tuesday       Latte          20
7  Thursday       Latte          30
6  Thursday    Espresso          40

### Finding values

- `loc` - Label based data selecting method which means that we have to pass `the name` of the row or columnt which we want to select. 
  - df.loc[ROWS, COLUMNS]
- `iloc` - Indexed-based selecting method which means that we have to pass an `integer index` in the method to select a specific row/column
  - df.iloc[ROWS, COLUMNS] # But only using integer index

#### loc

In [13]:
# Top three popular latte
df.loc[(df["Coffee Type"] == "Latte")].nlargest(3, columns=["Units Sold"])

         Day Coffee Type  Units Sold
9     Friday       Latte          35
11  Saturday       Latte          35
13    Sunday       Latte          35

In [14]:
# Selecting rows from 2 to 5 and specific columns
df.loc[2:5, ["Day", "Units Sold"]]

         Day  Units Sold
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35
5  Wednesday          25

#### iloc

In [15]:
df.iloc[:, :2]

          Day Coffee Type
0      Monday    Espresso
1      Monday       Latte
2     Tuesday    Espresso
3     Tuesday       Latte
4   Wednesday    Espresso
5   Wednesday       Latte
6    Thursday    Espresso
7    Thursday       Latte
8      Friday    Espresso
9      Friday       Latte
10   Saturday    Espresso
11   Saturday       Latte
12     Sunday    Espresso
13     Sunday       Latte

In [16]:
# Pretty the same like loc, but uses indexes instead of names.
df.iloc[2:5, [1, 2]]

  Coffee Type  Units Sold
2    Espresso          30
3       Latte          20
4    Espresso          35

#### Extra

In [17]:
# df.index = df["Day"]
# df = df.drop(columns=["Day"])

In [18]:
# df.loc["Monday":"Wednesday"]

### Finding specific value

- `at` - df.at[ROWS, COLUMNS]
- `iat` - df.iat[ROWS, COLUMNS] # Integer index based

#### iat

In [19]:
df.iat[0, 2]

np.int64(25)

#### at

In [20]:
df.at[0, "Units Sold"]

np.int64(25)

### Sorting

In [21]:
df.sort_values(["Units Sold", "Coffee Type"], ascending=False)  # or ascending=[0,1]

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
4   Wednesday    Espresso          35
7    Thursday       Latte          30
2     Tuesday    Espresso          30
5   Wednesday       Latte          25
0      Monday    Espresso          25
3     Tuesday       Latte          20
1      Monday       Latte          15

### Filtering data

In [22]:
bios = pd.read_csv(bios_file, index_col=0)
bios.info()

<class 'pandas.core.frame.DataFrame'>
Index: 145500 entries, 1 to 149814
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   name          145500 non-null  object
 1   born_date     143693 non-null  object
 2   born_city     110908 non-null  object
 3   born_region   110908 non-null  object
 4   born_country  110908 non-null  object
 5   NOC           145499 non-null  object
 6   height_cm     106651 non-null  float64
 7   weight_kg     102070 non-null  float64
 8   died_date     33940 non-null   object
dtypes: float64(2), object(7)
memory usage: 11.1+ MB

#### Filtering by height and width

In [23]:
bios.loc[(bios["height_cm"] >= 215), ["name", "height_cm"]].head()

                             name  height_cm
athlete_id
5108           Viktor Pankrashkin      220.0
5606         Paulinho Villas Boas      217.0
5622            Vladimir Andreyev      215.0
5696               Gunther Behnke      221.0
5739                     Uwe Blab      218.0

In [24]:
bios[(bios["height_cm"] >= 215) & (bios["weight_kg"] < 100)]

,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
athlete_id,,,,,,,,,
5622,Vladimir Andreyev,1945-06-14,Astrakhan,Astrakhan,RUS,Soviet Union,215.0,90.0,NaN
5819,Andy Campbell,1956-07-21,Melbourne,Victoria,AUS,Australia,218.0,93.0,NaN
82758,Gregor Fucka,1971-08-07,Kranj,Kranj,SLO,Italy,215.0,98.0,NaN
133148,Zhou Qi,1996-01-16,Xinxiang,Henan,CHN,People's Republic of China,217.0,95.0,NaN
144554,Yuta Watanabe,1994-10-13,Ayauta district,Kagawa,JPN,Japan,215.0,97.0,NaN

#### Filtering data where name starts with

In [25]:
bios.loc[bios["name"].str.contains(r"^Vlad|Pat")]

,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
athlete_id,,,,,,,,,
7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
120,Patrick Wheatley,1899-01-20,Vryheid,KwaZulu-Natal,RSA,Great Britain,NaN,NaN,1967-11-05
166,Patricia Offel,1971-12-19,NaN,NaN,NaN,Ghana,NaN,NaN,NaN
167,Patience Opokua,1969-06-17,NaN,NaN,NaN,Ghana,NaN,NaN,NaN
320,Patrick De Koning,1961-04-23,Dendermonde,Oost-Vlaanderen,BEL,Belgium,178.0,92.0,NaN
...,...,...,...,...,...,...,...,...,...
148626,Patriks Ozols,2001-02-02,Rīga,Rīga,LAT,Latvia,NaN,NaN,NaN
149139,Pat Nagle,1987-09-21,West Bloomfield Township,Michigan,USA,United States,NaN,NaN,NaN
149158,Patrick Gasienica,1998-11-28,McHenry,Illinois,USA,United States,NaN,NaN,2023-06-12
149190,Vladimir Tkachyov,1993-10-05,Dnipro,Dnipropetrovsk,UKR,ROC,183.0,84.0,NaN
149208,Vladislav Zharovtsev,1996-05-01,Minusinsk,Krasnoyarsk Kray,RUS,ROC,NaN,NaN,NaN

In [26]:
bios[bios["born_country"].isin(["USA"])]

,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
athlete_id,,,,,,,,,
55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...
149168,Kristen Santos,1994-11-02,Fairfield,Connecticut,USA,United States,NaN,NaN,NaN
149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN
149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN

#### Querying

In [27]:
bios.query("born_country == 'USA' and height_cm > 215")

,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
athlete_id,,,,,,,,,
5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

### Adding removing columns

#### Adding

In [28]:
df["Price"] = 4.99
df.head()

         Day Coffee Type  Units Sold  Price
0     Monday    Espresso          25   4.99
1     Monday       Latte          15   4.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

In [29]:
import numpy as np

In [30]:
df["New_Price"] = np.where(df["Coffee Type"] == "Espresso", 3.99, 5.99)
df.head()

         Day Coffee Type  Units Sold  Price  New_Price
0     Monday    Espresso          25   4.99       3.99
1     Monday       Latte          15   4.99       5.99
2    Tuesday    Espresso          30   4.99       3.99
3    Tuesday       Latte          20   4.99       5.99
4  Wednesday    Espresso          35   4.99       3.99

In [31]:
df["Revenue"] = df["New_Price"] * df["Units Sold"]
df.head()

         Day Coffee Type  Units Sold  Price  New_Price  Revenue
0     Monday    Espresso          25   4.99       3.99    99.75
1     Monday       Latte          15   4.99       5.99    89.85
2    Tuesday    Espresso          30   4.99       3.99   119.70
3    Tuesday       Latte          20   4.99       5.99   119.80
4  Wednesday    Espresso          35   4.99       3.99   139.65

#### Dropping

In [32]:
df = df.drop(columns=["Price"])  # df.drop(columns=["Price"], inplace=True)
df.head()

         Day Coffee Type  Units Sold  New_Price  Revenue
0     Monday    Espresso          25       3.99    99.75
1     Monday       Latte          15       5.99    89.85
2    Tuesday    Espresso          30       3.99   119.70
3    Tuesday       Latte          20       5.99   119.80
4  Wednesday    Espresso          35       3.99   139.65

#### Rename

In [33]:
df = df.rename(columns={"New_Price": "Price"})
df.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          15   5.99    89.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   3.99   139.65

### Cloning

Because Pandas (python) store references of DataFrame we need to copy object to not work on reference but new object.

In [34]:
coffee = df.copy()

print(f"References: {id(df)} != {id(coffee)}")

References: 5074231440 != 5253575632

## Adding columns

### Basic add

In [35]:
bios_copy = bios.copy()

In [36]:
bios_copy["first_name"] = bios["name"].str.split(" ").str[0]
bios_copy.head()

,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
athlete_id,,,,,,,,,,
1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert

### Datetime

In [37]:
bios["born_datetime"] = pd.to_datetime(bios["born_date"], format="%Y-%m-%d")

In [38]:
bios_copy["born_year"] = bios["born_datetime"].dt.year
bios_copy.head()

,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_year
athlete_id,,,,,,,,,,,
1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0
2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969.0
3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898.0
4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895.0
5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878.0

### Apply

In [39]:
bios_copy["height_category"] = bios["height_cm"].apply(
    lambda x: "Short" if x < 165 else ("Average" if x < 185 else "Tall")
)
bios_copy.head()

,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_year,height_category
athlete_id,,,,,,,,,,,,
1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,Tall
2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969.0,Average
3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898.0,Average
4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895.0,Average
5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878.0,Tall

In [40]:
def categorize_athlete(row):
    if row["height_cm"] <= 175 or row["weight_kg"] <= 75:
        return "Lightweight"
    if row["height_cm"] <= 185 or row["weight_kg"] <= 85:
        return "Middleweight"

    return "Heavyweight"

In [41]:
bios_copy["heavy_category"] = bios.apply(lambda x: categorize_athlete(x), axis=1)
bios_copy.head()

,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_year,height_category,heavy_category
athlete_id,,,,,,,,,,,,,
1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,Tall,Heavyweight
2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969.0,Average,Middleweight
3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898.0,Average,Middleweight
4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895.0,Average,Lightweight
5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878.0,Tall,Heavyweight

## Merging & Concatenating Data

Type of joins

![Type of joins](./images/types_of_joins.png)

### Merge BIO and NOC

In [42]:
bios.head()

,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime
athlete_id,,,,,,,,,,
1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12
2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01
3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13
4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895-05-11
5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878-04-17

In [43]:
nocs = pd.read_csv(noc_file)
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [44]:
bios_new = (
    pd.merge(bios, nocs, left_on="born_country", right_on="NOC", how="left")
    .drop(["notes", "NOC_y"], axis=1)
    .rename({"region": "born_country_full", "NOC_x": "NOC"}, axis=1)
)
bios_new.head()

,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,born_country_full
0,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12,France
1,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01,France
2,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13,France
3,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895-05-11,France
4,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878-04-17,UK

In [45]:
bios_new[bios_new["NOC"] != bios_new["born_country_full"]].head()

,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,born_country_full
4,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878-04-17,UK
12,J. Defert,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN,NaT,NaN
13,Étienne Durand,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN,NaT,NaN
16,Guy Forget,1965-01-04,Casablanca,Casablanca-Settat,MAR,France,189.0,79.0,NaN,1965-01-04,Morocco
27,"Guy, Baron Lejeune",NaN,NaN,NaN,NaN,France,NaN,NaN,NaN,NaT,NaN

### Merge RESULTS and BIO

In [46]:
results = pd.read_parquet(results_file)
results.head(1)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None

In [47]:
bios.head(1)

,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime
athlete_id,,,,,,,,,,
1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12

In [48]:
merged_df = pd.merge(results, bios, on="athlete_id", how="left")
merged_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,...,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12

### Concatenate

In [49]:
bios["born_country"].dropna().unique()
# bios[bios["born_country"].str.contains("USA", na=False)]

array(['FRA', 'GBR', 'MAR', 'FPN', 'IRQ', 'USA', 'RSA', 'IRL', 'IND',
       'CHN', 'JAM', 'AUS', 'CAN', 'GER', 'ROU', 'BRA', 'CZE', 'RUS',
       'GRE', 'EGY', 'HUN', 'POL', 'MEX', 'SRB', 'SVK', 'INA', 'SRI',
       'PAK', 'ESP', 'AUT', 'BEL', 'BLR', 'BUL', 'CRC', 'DEN', 'EST',
       'FIN', 'SUI', 'GEO', 'ARG', 'ARM', 'BAH', 'CAM', 'CHI', 'ISR',
       'UZB', 'ITA', 'JPN', 'KOR', 'LAT', 'UKR', 'LTU', 'LUX', 'MAD',
       'MAS', 'MRI', 'NED', 'NGR', 'NOR', 'TUR', 'NZL', 'PAR', 'PER',
       'BAR', 'HKG', 'GUY', 'CGO', 'COD', 'CMR', 'COL', 'PUR', 'TPE',
       'VIE', 'CUB', 'DOM', 'CRO', 'ECU', 'ESA', 'MDA', 'MGL', 'ZIM',
       'PHI', 'POR', 'SLO', 'SWE', 'TJK', 'CIV', 'BIH', 'THA', 'CAF',
       'ALG', 'PRK', 'KAZ', 'UGA', 'TTO', 'TUN', 'AZE', 'URU', 'MYA',
       'VEN', 'ETH', 'FIJ', 'SEN', 'LBA', 'GAB', 'NCA', 'CUR', 'ARU',
       'ANG', 'Cologne', 'KOS', 'GHA', 'GUA', 'TLS', 'NEP', 'IRI', 'KEN',
       'KGZ', 'LBR', 'MAW', 'MLI', 'NAM', 'CPV', 'SUR', 'SLE', 'NIG',
       'PAN', 'SAM', 'TKM', 'MKD', 'SGP', 'MNE', 'SYR', 'MON', 'PNG',
       'BEN', 'ZAM', 'SUD', 'SSD', 'BDI', 'TAN', 'VAN', 'BOL', 'MLT',
       'JER', 'KSA', 'MOZ', 'BER', 'GRL', 'LBN', 'CYP', 'SMR', 'ERI',
       'LIE', 'GUM', 'BIZ', 'CAY', 'ALB', 'AND', 'Spreewald', 'MTS',
       'HAI', 'IOM', 'FLI', 'BAN', 'Vienna', 'NCD', 'GUI', 'KUW', 'STP',
       'GBS', 'QAT', 'SOM', 'TOG', 'Elster', 'ISL', 'Saale', 'Milde',
       'GIB', 'BUR', 'GUE', 'JOR', 'OMA', 'NFI', 'BRN', 'YEM', 'DMA',
       'GEQ', 'HON', 'SWZ', 'Prignitz', 'ANT', 'NRU', 'AFG', 'Altmark',
       'Munich', 'BOT', 'VIN', 'SKN', 'CHA', 'COM', 'DJI', 'MRT', 'MQE',
       'GAM', 'AGU', 'SEY', 'Havel', 'Luppe', 'GRN', 'LCA', 'PLE', 'SOL',
       'ASA', 'BHU', 'Upland', 'SMT', 'PLW', 'LES', 'UAE', 'TKS', 'KIR',
       'MDV', 'RWA', 'FSM', 'LAO', 'TGA', 'MHL', 'TUV', 'FAR', 'BRU',
       'MTN', 'COK', 'Corfu', 'IVB', 'Aarhus'], dtype=object)

In [50]:
usa = bios[bios["born_country"] == "USA"]
display("USA size ", usa.size)
gbr = bios[bios["born_country"] == "GBR"]
display("GBR size ", gbr.size)

'USA size '

96410

'GBR size '

57920

In [51]:
new_df = pd.concat([usa, gbr]).sample(frac=1)
new_df.head()

,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime
athlete_id,,,,,,,,,,
68,Dorothy Shepherd-Barron,1897-11-24,Beighton,England,GBR,Great Britain,NaN,NaN,1953-02-20,1897-11-24
32960,Walter Bowden,1910-12-29,New York,New York,USA,United States,NaN,NaN,2001-04-19,1910-12-29
62996,John Merricks,1971-02-16,Leicester,England,GBR,Great Britain,173.0,62.0,1997-10-08,1971-02-16
124569,Natasha Tang,1992-08-23,Westminster,England,GBR,"Hong Kong, China",165.0,54.0,NaN,1992-08-23
130261,Claire Allan,1985-05-07,Isleworth,England,GBR,Great Britain,170.0,65.0,NaN,1985-05-07

## Handling NULL values

In [52]:
df_new = df.copy()
df_new.loc[0:1, "Units Sold"] = np.nan
df_new.isna().sum()  # Clear vision that some of columns contain NaN value

Day            0
Coffee Type    0
Units Sold     2
Price          0
Revenue        0
dtype: int64

In [53]:
display(df_new[df_new["Units Sold"].isna()].head())
display(df_new[df_new["Units Sold"].notna()].head())

      Day Coffee Type  Units Sold  Price  Revenue
0  Monday    Espresso         NaN   3.99    99.75
1  Monday       Latte         NaN   5.99    89.85

         Day Coffee Type  Units Sold  Price  Revenue
2    Tuesday    Espresso        30.0   3.99   119.70
3    Tuesday       Latte        20.0   5.99   119.80
4  Wednesday    Espresso        35.0   3.99   139.65
5  Wednesday       Latte        25.0   5.99   149.75
6   Thursday    Espresso        40.0   3.99   159.60

### Setting values by hand.

In [54]:
# df_new["Units Sold"] = df_new["Units Sold"].fillna(0)
df_new.fillna(df_new["Units Sold"].mean())
df.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          15   5.99    89.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   3.99   139.65

### Dropping rows.

In [55]:
df_new = df.copy()
df_new.loc[0:1, "Units Sold"] = np.nan
df_new.isna().sum()

Day            0
Coffee Type    0
Units Sold     2
Price          0
Revenue        0
dtype: int64

In [56]:
df_new = df_new.dropna(subset=["Units Sold"])
df_new.head()

         Day Coffee Type  Units Sold  Price  Revenue
2    Tuesday    Espresso        30.0   3.99   119.70
3    Tuesday       Latte        20.0   5.99   119.80
4  Wednesday    Espresso        35.0   3.99   139.65
5  Wednesday       Latte        25.0   5.99   149.75
6   Thursday    Espresso        40.0   3.99   159.60

## Aggregating data

### Basic aggregation (Value_Count)

In [57]:
bios.head()

,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime
athlete_id,,,,,,,,,,
1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12
2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01
3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13
4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895-05-11
5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878-04-17

In [58]:
# Count number of cities
bios["born_country"].value_counts()

born_country
USA        9641
GER        6891
GBR        5792
FRA        5143
ITA        4709
           ...
GIB           1
NFI           1
Munich        1
Altmark       1
Aarhus        1
Name: count, Length: 236, dtype: int64

In [59]:
# Count region athletes from POL
bios[bios["born_country"] == "POL"]["born_region"].value_counts()

born_region
Śląskie                427
Małopolskie            389
Mazowieckie            388
Dolnośląskie           253
Wielkopolskie          251
Pomorskie              213
Kujawsko-Pomorskie     181
Łódzkie                158
Zachodniopomorskie     121
Warmińsko-Mazurskie    119
Lubuskie               103
Podkarpackie            94
Lubelskie               83
Opolskie                58
Podlaskie               54
Świętokrzyskie          50
Name: count, dtype: int64

### GroupBy

In [60]:
df.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          15   5.99    89.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   3.99   139.65

In [61]:
display(df.groupby(["Coffee Type"])["Units Sold"].sum())
display(df.groupby(["Coffee Type"])["Units Sold"].mean())

Coffee Type
Espresso    265
Latte       195
Name: Units Sold, dtype: int64

Coffee Type
Espresso    37.857143
Latte       27.857143
Name: Units Sold, dtype: float64

In [62]:
df.groupby("Coffee Type").agg({"Units Sold": "sum", "Price": "mean"})

             Units Sold  Price
Coffee Type
Espresso            265   3.99
Latte               195   5.99

In [63]:
df.groupby(["Day", "Coffee Type"]).agg({"Units Sold": "sum"})

                       Units Sold
Day       Coffee Type
Friday    Espresso             45
          Latte                35
Monday    Espresso             25
          Latte                15
Saturday  Espresso             45
          Latte                35
Sunday    Espresso             45
          Latte                35
Thursday  Espresso             40
          Latte                30
Tuesday   Espresso             30
          Latte                20
Wednesday Espresso             35
          Latte                25

### Pivot

In [64]:
df.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          15   5.99    89.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   3.99   139.65

In [65]:
display(df.pivot(columns="Coffee Type", index="Day"))
display(df.pivot(columns="Coffee Type", index="Day", values=["Revenue"]))

            Units Sold          Price        Revenue
Coffee Type   Espresso Latte Espresso Latte Espresso   Latte
Day
Friday              45    35     3.99  5.99   179.55  209.65
Monday              25    15     3.99  5.99    99.75   89.85
Saturday            45    35     3.99  5.99   179.55  209.65
Sunday              45    35     3.99  5.99   179.55  209.65
Thursday            40    30     3.99  5.99   159.60  179.70
Tuesday             30    20     3.99  5.99   119.70  119.80
Wednesday           35    25     3.99  5.99   139.65  149.75

             Revenue
Coffee Type Espresso   Latte
Day
Friday        179.55  209.65
Monday         99.75   89.85
Saturday      179.55  209.65
Sunday        179.55  209.65
Thursday      159.60  179.70
Tuesday       119.70  119.80
Wednesday     139.65  149.75

### Olympics

In [66]:
bios.head()

,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime
athlete_id,,,,,,,,,,
1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12
2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01
3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13
4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895-05-11
5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878-04-17

In [67]:
# 1972 year the most popular to be born for Olympic Athletes
bios.groupby(bios["born_datetime"].dt.year)["name"].count().reset_index().sort_values(
    by="name", ascending=False
)

     born_datetime  name
139         1972.0  2231
152         1985.0  2227
140         1973.0  2216
138         1971.0  2205
137         1970.0  2174
..             ...   ...
5           1838.0     1
4           1837.0     1
3           1836.0     1
2           1833.0     1
176         2009.0     1

[177 rows x 2 columns]

## Shift | Rank | Rolling | Cumsum

### Shift

Shift index by desired number of periods with an optional time freq.

In [68]:
coffee.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          15   5.99    89.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   3.99   139.65

In [69]:
coffee["Yesterday_Revenue"] = coffee['Revenue'].shift(2)
coffee.head()

         Day Coffee Type  Units Sold  Price  Revenue  Yesterday_Revenue
0     Monday    Espresso          25   3.99    99.75                NaN
1     Monday       Latte          15   5.99    89.85                NaN
2    Tuesday    Espresso          30   3.99   119.70              99.75
3    Tuesday       Latte          20   5.99   119.80              89.85
4  Wednesday    Espresso          35   3.99   139.65             119.70

In [70]:
coffee['PCT_Change'] = coffee['Revenue'] / coffee['Yesterday_Revenue'] * 100
coffee.head()

,Day,Coffee Type,Units Sold,Price,Revenue,Yesterday_Revenue,PCT_Change
0,Monday,Espresso,25,3.99,99.75,NaN,NaN
1,Monday,Latte,15,5.99,89.85,NaN,NaN
2,Tuesday,Espresso,30,3.99,119.70,99.75,120.000000
3,Tuesday,Latte,20,5.99,119.80,89.85,133.333333
4,Wednesday,Espresso,35,3.99,139.65,119.70,116.666667

### Rank

Compute numerical data ranks (1 through n) along axis.

In [71]:
bios['height_rank'] = bios['height_cm'].rank(ascending=False)
bios.sort_values('height_rank')

,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,height_rank
athlete_id,,,,,,,,,,,
89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN,1980-09-12,1.0
7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN,1964-12-19,2.5
5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN,1952-02-24,2.5
122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN,1987-11-18,5.0
89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN,1975-11-01,5.0
...,...,...,...,...,...,...,...,...,...,...,...
149217,Sin Ye-Chan,1995-06-13,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN,1995-06-13,NaN
149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN,1989-12-05,NaN
149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24,1927-04-24,NaN
149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,1998-08-31,NaN
149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,1913-07-15,NaN

### Cumsum

In [72]:
coffee.head()

,Day,Coffee Type,Units Sold,Price,Revenue,Yesterday_Revenue,PCT_Change
0,Monday,Espresso,25,3.99,99.75,NaN,NaN
1,Monday,Latte,15,5.99,89.85,NaN,NaN
2,Tuesday,Espresso,30,3.99,119.70,99.75,120.000000
3,Tuesday,Latte,20,5.99,119.80,89.85,133.333333
4,Wednesday,Espresso,35,3.99,139.65,119.70,116.666667

In [73]:
coffee['Cumulative_Revenue'] = coffee['Revenue'].cumsum()
coffee

,Day,Coffee Type,Units Sold,Price,Revenue,Yesterday_Revenue,PCT_Change,Cumulative_Revenue
0,Monday,Espresso,25,3.99,99.75,NaN,NaN,99.75
1,Monday,Latte,15,5.99,89.85,NaN,NaN,189.60
2,Tuesday,Espresso,30,3.99,119.70,99.75,120.000000,309.30
3,Tuesday,Latte,20,5.99,119.80,89.85,133.333333,429.10
4,Wednesday,Espresso,35,3.99,139.65,119.70,116.666667,568.75
5,Wednesday,Latte,25,5.99,149.75,119.80,125.000000,718.50
6,Thursday,Espresso,40,3.99,159.60,139.65,114.285714,878.10
7,Thursday,Latte,30,5.99,179.70,149.75,120.000000,1057.80
8,Friday,Espresso,45,3.99,179.55,159.60,112.500000,1237.35
9,Friday,Latte,35,5.99,209.65,179.70,116.666667,1447.00
10,Saturday,Espresso,45,3.99,179.55,179.55,100.000000,1626.55
11,Saturday,Latte,35,5.99,209.65,209.65,100.000000,1836.20
12,Sunday,Espresso,45,3.99,179.55,179.55,100.000000,2015.75
13,Sunday,Latte,35,5.99,209.65,209.65,100.000000,2225.40